"""Added lazy load to conversations and users in participants

Revision ID: a66547f68d1b
Revises: 7c738a0ca04a
Create Date: 2026-08-15 18:54:22.289684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66547f68d1b'
down_revision: Union[str, Sequence[str], None] = '7c738a0ca04a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
