"""Added back_populates to Message

Revision ID: 841bcfdff175
Revises: 8f6ed0bd27fd
Create Date: 2026-08-28 18:52:23.242443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '841bcfdff175'
down_revision: Union[str, Sequence[str], None] = '8f6ed0bd27fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
