"""Added device ID, this time real

Revision ID: 48ef85db7b26
Revises: 66f2fb74f58f
Create Date: 2026-08-26 20:28:33.289107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48ef85db7b26'
down_revision: Union[str, Sequence[str], None] = '66f2fb74f58f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.add_column('refresh_tokens', sa.Column('device_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_refresh_tokens_device_id'), 'refresh_tokens', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_device_id'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'device_id')
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('custom_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_profiles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_profiles_pkey'))
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('theme', postgresql.ENUM('SYSTEM', 'LIGHT', 'DARK', name='theme'), autoincrement=False, nullable=False),
    sa.Column('language', postgresql.ENUM('EN', 'HI', name='language'), autoincrement=False, nullable=False),
    sa.Column('notifications_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('message_notifications', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('mention_notifications', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sound_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('profile_visibility', postgresql.ENUM('EVERYONE', 'CONTACTS', 'NOBODY', name='visibility'), autoincrement=False, nullable=False),
    sa.Column('avatar_visibility', postgresql.ENUM('EVERYONE', 'CONTACTS', 'NOBODY', name='visibility'), autoincrement=False, nullable=False),
    sa.Column('last_seen_visibility', postgresql.ENUM('EVERYONE', 'CONTACTS', 'NOBODY', name='visibility'), autoincrement=False, nullable=False),
    sa.Column('read_receipts_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('enter_to_send', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('media_auto_download', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_settings_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_settings_pkey'))
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    # ### end Alembic commands ###
