"""add conversation metadata and message replies reactions

Revision ID: 7971d5a8deed
Revises: fb5b65163ea4
Create Date: 2026-08-16 14:15:05.492366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7971d5a8deed'
down_revision: Union[str, Sequence[str], None] = 'fb5b65163ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('conversations', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column(
    'conversations',
    sa.Column(
        'settings',
        postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        server_default=sa.text("'{}'::jsonb")
    )
)

    op.add_column('messages', sa.Column('reply_to_message_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_messages_reply_to_message_id'), 'messages', ['reply_to_message_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_reply_to_message_id'), table_name='messages')
    op.drop_column('messages', 'reply_to_message_id')
    op.drop_column('conversations', 'settings')
    op.drop_column('conversations', 'avatar_url')
    op.drop_column('conversations', 'description')
    # ### end Alembic commands ###
