"""Changed the constraints on conversation_id and user_id in participants

Revision ID: 7c738a0ca04a
Revises: 8bee2036b318
Create Date: 2026-08-15 18:45:11.324928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c738a0ca04a'
down_revision: Union[str, Sequence[str], None] = '8bee2036b318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
